### ISSUE TITLE
ALEPH-126 - Upgrade pydantic version

### ISSUE THREAD

**Issue by RezaRahemtola** [aleph-im/aleph-message#108]
The current version of pydantic used is `<2.0.0`, while the 2.0 has been out for [more than a year](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/) now (in fact we are at `v2.9.1` atm).

This means that for newly created projects, installing pydantic then `aleph-sdk-python` (that depends on `aleph-message`) throws an error and forces the user to downgrade their pydantic version, which might be problematic (not in this specific case for me, but at LibertAI we have our agents framework that requires features of pydantic v2, so people won't be able to use it with the aleph-sdk)
<img width="972" alt="image" src="https://github.com/user-attachments/assets/ec2bc600-2855-4a69-854e-33c2fe3bffff">

**Comment by RezaRahemtola** [comment]
cc @philogicae @hoh

**Comment by hoh** [comment]
The main motivation for staying on pydantic 1 was that it was [the version packaged on Debian stabe](https://packages.debian.org/bookworm/python3-pydantic).

I believe that given the additional constraints we have now, `aleph-message` should either be made compatible with both versions or `aleph-vm` should vendor pydantic 2.
