### ISSUE TITLE
Computing item_hash does not support non-inline message storage

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-message#17]
See https://github.com/aleph-im/aleph-client/blob/3b7383bc4b6ec479cfc42d111622b8a8a1b9a4ea/src/aleph_client/asynchronous.py#L436-L450

Related to https://github.com/aleph-im/aleph-client/pull/106

**Comment by MHHukiewitz** [comment]
Should be fixed, as we compute the item_hash directly from the json dump here:

https://github.com/aleph-im/aleph-sdk-python/blob/59e22b5ee52ce8400311d7fc287a8cfcc037930c/src/aleph/sdk/client/authenticated_http.py#L606

and here:

https://github.com/aleph-im/aleph-message/blob/e1c0f474c394e2f7ce380d97dfac71bec157f056/aleph_message/models/__init__.py#L375
