### ISSUE TITLE
Unit unclear for MachineResources.memory

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-message#41]
This field is mapped to Mebibytes (MiB) [in aleph-vm](https://github.com/aleph-im/aleph-vm/blob/df99175750e993a7fcb6e181135358789d18674f/vm_supervisor/vm/firecracker_microvm.py#L304), but it is not clear that the unit is Mebibytes in this project.

**Comment by MHHukiewitz** [comment]
Has been solved: https://github.com/aleph-im/aleph-message/blob/main/aleph_message/models/execution/environment.py#L64
