### ISSUE TITLE
As a user of Programs or Instances, I can specify a custom domain for my VM

### ISSUE THREAD

**Issue by hoh** [aleph-im/aleph-message#67]
- [ ]  The message must contain the custom domain of the user.
- [ ] The ownership of the domain is validated by a TXT record containing the user's address
- [ ] The user must configure a CNAME pointing to aleph.im's DNS servers or a copy

**Comment by MHHukiewitz** [comment]
Can now be done using
- the SDK: https://github.com/aleph-im/aleph-sdk-python/pull/55
- and the client: https://github.com/aleph-im/aleph-client/pull/167
